import { CompanionCharacter } from "./types";

export const COMPANIONS: CompanionCharacter[] = [
  {
    id: "alchemist",
    name: "companion.alchemist.name",
    description: "companion.alchemist.description",
    idleGif: "/character gifs/Alchemist.gif",
    celebrationGif: "/character gifs/Alchemist.gif",
    encouragementGif: "/character gifs/Alchemist.gif",
  },
  {
    id: "devils_snare",
    name: "companion.devils_snare.name",
    description: "companion.devils_snare.description",
    idleGif: "/character gifs/Devil's Snare.gif",
    celebrationGif: "/character gifs/Devil's Snare.gif",
    encouragementGif: "/character gifs/Devil's Snare.gif",
  },
  {
    id: "elite_knight",
    name: "companion.elite_knight.name",
    description: "companion.elite_knight.description",
    idleGif: "/character gifs/Elite Knight.gif",
    celebrationGif: "/character gifs/Elite Knight.gif",
    encouragementGif: "/character gifs/Elite Knight.gif",
  },
  {
    id: "grand_knight",
    name: "companion.grand_knight.name",
    description: "companion.grand_knight.description",
    idleGif: "/character gifs/Grand Knight.gif",
    celebrationGif: "/character gifs/Grand Knight.gif",
    encouragementGif: "/character gifs/Grand Knight.gif",
  },
  {
    id: "grand_wizard",
    name: "companion.grand_wizard.name",
    description: "companion.grand_wizard.description",
    idleGif: "/character gifs/Grand Wizard.gif",
    celebrationGif: "/character gifs/Grand Wizard.gif",
    encouragementGif: "/character gifs/Grand Wizard.gif",
  },
  {
    id: "knight",
    name: "companion.knight.name",
    description: "companion.knight.description",
    idleGif: "/character gifs/Knight.gif",
    celebrationGif: "/character gifs/Knight.gif",
    encouragementGif: "/character gifs/Knight.gif",
  },
  {
    id: "lava_knight",
    name: "companion.lava_knight.name",
    description: "companion.lava_knight.description",
    idleGif: "/character gifs/Lava Knight.gif",
    celebrationGif: "/character gifs/Lava Knight.gif",
    encouragementGif: "/character gifs/Lava Knight.gif",
  },
  {
    id: "phantom_king",
    name: "companion.phantom_king.name",
    description: "companion.phantom_king.description",
    idleGif: "/character gifs/Phantom King.gif",
    celebrationGif: "/character gifs/Phantom King.gif",
    encouragementGif: "/character gifs/Phantom King.gif",
  },
  {
    id: "skeleton_king",
    name: "companion.skeleton_king.name",
    description: "companion.skeleton_king.description",
    idleGif: "/character gifs/Skeleton King.gif",
    celebrationGif: "/character gifs/Skeleton King.gif",
    encouragementGif: "/character gifs/Skeleton King.gif",
  },
  {
    id: "special_force_blue",
    name: "companion.special_force_blue.name",
    description: "companion.special_force_blue.description",
    idleGif: "/character gifs/Special Force - Code_BLUE.gif",
    celebrationGif: "/character gifs/Special Force - Code_BLUE.gif",
    encouragementGif: "/character gifs/Special Force - Code_BLUE.gif",
  },
  {
    id: "special_force_green",
    name: "companion.special_force_green.name",
    description: "companion.special_force_green.description",
    idleGif: "/character gifs/Special Force - Code_GREEN.gif",
    celebrationGif: "/character gifs/Special Force - Code_GREEN.gif",
    encouragementGif: "/character gifs/Special Force - Code_GREEN.gif",
  },
  {
    id: "special_force_red",
    name: "companion.special_force_red.name",
    description: "companion.special_force_red.description",
    idleGif: "/character gifs/Special Force - Code_RED.gif",
    celebrationGif: "/character gifs/Special Force - Code_RED.gif",
    encouragementGif: "/character gifs/Special Force - Code_RED.gif",
  },
  {
    id: "witch",
    name: "companion.witch.name",
    description: "companion.witch.description",
    idleGif: "/character gifs/Witch of the Mist.gif",
    celebrationGif: "/character gifs/Witch of the Mist.gif",
    encouragementGif: "/character gifs/Witch of the Mist.gif",
  },
  {
    id: "rogue_1",
    name: "companion.rogue_1.name",
    description: "companion.rogue_1.description",
    idleGif: "/character gifs/download (1).gif",
    celebrationGif: "/character gifs/download (1).gif",
    encouragementGif: "/character gifs/download (1).gif",
  },
  {
    id: "rogue_2",
    name: "companion.rogue_2.name",
    description: "companion.rogue_2.description",
    idleGif: "/character gifs/download.gif",
    celebrationGif: "/character gifs/download.gif",
    encouragementGif: "/character gifs/download.gif",
  },
];

export function getCompanion(id: string): CompanionCharacter | undefined {
  return COMPANIONS.find((c) => c.id === id);
}
